name: Backfill Commit Comparison Generator

on:
  workflow_dispatch:
    inputs:
      startDate:
        description: "Start date for commit range. (UTC; ISO 8601; required)"
        required: true
      endDate:
        description: "End date for commit range. (UTC; ISO 8601; required)"
        required: true

jobs:
  commit-compare:
    runs-on: ubuntu-latest
    name: Commit Comparer
    steps:
#      - name: Get current date
#        id: datetime
#        run: echo "current_datetime_minus_1h=$(date -u --date="1 hour ago" +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
#      - name: Install dependencies
#        run: npm ci
#      - name: Generate manifest.json
#        run: npm run build
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run report+json generator process
        run: |
          .github/workflows/scripts/.pinot_backfill_commit_compare.sh ${{ github.event.inputs.startDate }} ${{ github.event.inputs.endDate }}
      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Add PR reports"
            git push
          else
            echo "No commits made in last 30 minutes."
          fi
