name: date test

on:
  workflow_dispatch:
    inputs:
      ijioj:
        description: "eofijne2gio23heigo24"
        required: false

jobs:
  commit-compare:
    runs-on: ubuntu-latest
    name: blech
    steps:
      - name: Get current date
        id: datetime
        run: echo "last_workflow_run=$(gh run list -R matvj250/test_repo_2_for_cloning --workflow commit_report_realtime.yml --status success --limit 1 --json startedAt --jq '.[] | .startedAt')" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.COMMIT_CHANGE_REPORT }}
      - name: Check out code
        uses: actions/checkout@v3
      - name: test
        run: echo "$last_workflow_run"
      # - name: george clooney
      #   run: |
      #     test/eekyeepy.sh "$current_datetime_minus_30m"
      #   env:
      #     GH_TOKEN: ${{ secrets.COMMIT_CHANGE_REPORT }}
