name: date test

on:
  schedule:
    - cron: "*/5 * * * *" #every 4 minutes

jobs:
  commit-compare:
    runs-on: ubuntu-latest
    name: blech
    steps:
      - name: Get current date
        id: datetime
#        run: date -u -v-2H +"%Y-%m-%dT%H:%M:%SZ"
        run: echo "current_datetime_minus_30m=$(date -u -v-2H +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
#      - name: Check out code
#        uses: actions/checkout@v3
      - name: Check out code
        uses: actions/checkout@v3
      - name: george clooney
        run: |
          test/eekyeepy.sh $1
        env:
          GH_TOKEN: ${{ secrets.COMMIT_CHANGE_REPORT }}