name: date test

on:
  workflow_dispatch:
    inputs:
      ijioj:
        description: "eofijne2gio23heigo24"
        required: false

jobs:
  commit-compare:
    runs-on: ubuntu-latest
    name: blech
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run report+json generator process
        run: |
          test/eekyeepy.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
