name: date test

on:
  schedule:
    - cron: "0 0 1 1 0"

jobs:
  commit-compare:
    runs-on: ubuntu-latest
    name: blech
    steps:
      - name: Get current date
        id: datetime
#        run: date -u -v-2H +"%Y-%m-%dT%H:%M:%SZ"
        run: echo "current_datetime_minus_30m=$(date -u --date="2 hours ago" +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
      - name: Check out code
        uses: actions/checkout@v3
      - name: test
        run: echo "$current_datetime_minus_30m"
      - name: george clooney
        run: |
          test/eekyeepy.sh "$current_datetime_minus_30m"
        env:
          GH_TOKEN: ${{ secrets.COMMIT_CHANGE_REPORT }}
